# Generated by Django 5.1.2 on 2024-11-01 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('arena', models.CharField(max_length=100)),
                ('broadcast', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=20, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('home_team_score', models.IntegerField(blank=True, null=True)),
                ('away_team_score', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('team_id', models.IntegerField()),
                ('team_abbreviation', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('w_pct', models.FloatField()),
                ('min', models.FloatField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg_pct', models.FloatField()),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('fg3_pct', models.FloatField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft_pct', models.FloatField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('plus_minus', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamListTeam',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('conference', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamListPlayer',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_number', models.CharField(max_length=3)),
                ('position', models.CharField(max_length=5)),
                ('age', models.IntegerField(null=True)),
                ('gp', models.IntegerField(default=0)),
                ('min', models.FloatField(default=0)),
                ('pts', models.FloatField(default=0)),
                ('reb', models.FloatField(default=0)),
                ('ast', models.FloatField(default=0)),
                ('stl', models.FloatField(default=0)),
                ('blk', models.FloatField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='SportsSyncApi.teamlistteam')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'team_id')},
            },
        ),
    ]
