# Generated by Django 5.1.2 on 2024-10-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsSyncApi', '0002_game_team_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('team_id', models.IntegerField()),
                ('team_abbreviation', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('w_pct', models.FloatField()),
                ('min', models.FloatField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg_pct', models.FloatField()),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('fg3_pct', models.FloatField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft_pct', models.FloatField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('plus_minus', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
