from rest_framework import serializers

class PlayerListSerializer(serializers.Serializer):
    player_id = serializers.IntegerField()
    player_name = serializers.CharField(max_length=100)
    nickname = serializers.CharField(required=False, allow_blank=True)
    team_id = serializers.IntegerField()
    team_abbreviation = serializers.CharField(max_length=10)
    age = serializers.IntegerField(required=False)
    gp = serializers.IntegerField()
    w = serializers.IntegerField()
    l = serializers.IntegerField()
    w_pct = serializers.FloatField()
    min = serializers.FloatField()
    fgm = serializers.IntegerField()
    fga = serializers.IntegerField()
    fg_pct = serializers.FloatField()
    fg3m = serializers.IntegerField()
    fg3a = serializers.IntegerField()
    fg3_pct = serializers.FloatField()
    ftm = serializers.IntegerField()
    fta = serializers.IntegerField()
    ft_pct = serializers.FloatField()
    oreb = serializers.IntegerField()
    dreb = serializers.IntegerField()
    reb = serializers.IntegerField()
    ast = serializers.IntegerField()
    tov = serializers.IntegerField()
    stl = serializers.IntegerField()
    blk = serializers.IntegerField()
    pts = serializers.IntegerField()
    plus_minus = serializers.FloatField()

class PlayerDetailSerializer(serializers.Serializer):
    player_id = serializers.IntegerField(source='PLAYER_ID')
    player_name = serializers.CharField(source='PLAYER_NAME', max_length=100)
    team_id = serializers.IntegerField(source='TEAM_ID')
    team_abbreviation = serializers.CharField(source='TEAM_ABBREVIATION', max_length=10)
    gp = serializers.IntegerField(source='GP')
    w = serializers.IntegerField(source='W')
    l = serializers.IntegerField(source='L')
    w_pct = serializers.FloatField(source='W_PCT')
    min = serializers.FloatField(source='MIN')
    fgm = serializers.IntegerField(source='FGM')
    fga = serializers.IntegerField(source='FGA')
    fg_pct = serializers.FloatField(source='FG_PCT')
    fg3m = serializers.IntegerField(source='FG3M')
    fg3a = serializers.IntegerField(source='FG3A')
    fg3_pct = serializers.FloatField(source='FG3_PCT')
    ftm = serializers.IntegerField(source='FTM')
    fta = serializers.IntegerField(source='FTA')
    ft_pct = serializers.FloatField(source='FT_PCT')
    oreb = serializers.IntegerField(source='OREB')
    dreb = serializers.IntegerField(source='DREB')
    reb = serializers.IntegerField(source='REB')
    ast = serializers.IntegerField(source='AST')
    tov = serializers.IntegerField(source='TOV')
    stl = serializers.IntegerField(source='STL')
    blk = serializers.IntegerField(source='BLK')
    pts = serializers.IntegerField(source='PTS')
    plus_minus = serializers.FloatField(source='PLUS_MINUS')